---

# Iniital Configuration of Digital Substation Switches
# if individual settings are commented out, it's because they are default and do not show in the
#   running config. They are commented out so that they will not show a "changed" status in the
#   ansible results. 

- name: Configure Cisco IOS Devices
  hosts: all
  gather_facts: false
  tasks:
#   This task is for testing to see which switches are being configured
    # - name: Working on the following switches
    #   ansible.builtin.debug:
    #     msg: "{{ host_name }}"

    - name: Set switch hostname
      cisco.ios.ios_hostname:
        config:
          hostname: "{{ host_name }}"

    - name: Set the logon banner
      cisco.ios.ios_banner:
        state: present
        banner: login
        text: "{{ lookup('file', './files/logon_banner') }}"

    - name: Turn off Console Logging
      cisco.ios.ios_config:
        lines:
          - no logging console

    - name: Turn off VTP, CDP, LLDP
      cisco.ios.ios_config:
        lines:
          - vtp mode off
          - no cdp run
          # - no lldp run   # lldp is off by default

# Password recovery seems to be disabled by default. Will need to verify 
    - name: Password recovery information
      ansible.builtin.debug:
        msg: |
          Password recovery will be disabled. 
          The password can still be reset, but this will 
              require as factory reset of the switch to do so.
          If a reset is performed, you will need to re-enable SSH and
              re-run this playbook. 

    - name: Disabling password recovery (i.e. password recovery requires a system reset)
      # cisco.ios.ios_config:
      #   lines: no service password-recovery
      cisco.ios.ios_service:
        config:
          state: merged
          password_recovery: false

    - name: Create Ansible and main user
      cisco.ios.ios_user:
        aggregate:
          - name: "network_viewer"
            configured_password: "{{ view_only_password }}" 
            password_type: "secret"
            privilege: 3
          - name: "ansible"
            configured_password: "{{ ansible_password }}"
            password_type: "secret"
            # update_password: "on_create"
            privilege: 15
            sshkey:
              - "{{ lookup('file', '~/.ssh/ansible_key.pub') }}"
        state: present
    
    - name: Enable the SCP server for remote backups
      cisco.ios.ios_config:
        lines:
          - aaa new-model
          - aaa authentication login default local
          - aaa authorization exec default local
          # - ip ssh version 2   # default version of ssh
          - ip scp server enable

    - name: Ensuring passwords are encrypted
      cisco.ios.ios_service:
        state: merged
        config:
          password_encryption: true

    - name: Configuring logging timestamps
      cisco.ios.ios_service:
        state: merged
        config:
          timestamps:
            - msg: log
              timestamp: datetime
              datetime_options:
                msec: true
                year: true
            - msg: debug
              timestamp: datetime
              datetime_options:
                msec: true
                year: true

    - name: Setting the switch as a PTP transparent clock 
      cisco.ios.ios_config:
        lines: 
          - "ptp clock transparent domain {{ ptp_domain }}  profile {{ ptp_profile }}"
          # - exit

    - name: Creating VLANs
      cisco.ios.ios_vlans:
        state: merged
        config:
          # vlan 1 is default so it does not need to be specified
          # - vlan_id: 1
          #   name: unused_native
          - vlan_id: 40
            name: process_bus_a
          - vlan_id: 41
            name: process_bus_b
          - vlan_id: 60
            name: pb-prpa
          - vlan_id: 61
            name: pb-prpb
          - vlan_id: 140
            name: station_bus_a
          - vlan_id: 141
            name: station_bus_b
          - vlan_id: 20
            name: sb-prpa
          - vlan_id: 21
            name: sb-prpb
          - vlan_id: 10
            name: management
          - vlan_id: 40
            name: ptp
          - vlan_id: 15
            name: monitoring


    - name: Configuring interface port names
      cisco.ios.ios_interfaces:
        state: replaced
        config: "{{ interface_names }}"
    
    - name: Configuring switchport vlan parameters
      cisco.ios.ios_l2_interfaces:
        state: replaced
        config: "{{ switchports }}"

    - name: Configure Logging
    # used for creating the syslog server for the switch
    # the commented commands will cause change status every time playbook is run
      cisco.ios.ios_logging_global:
        config:
#          logging_on: enable # causes changed status
          trap: errors  # making this "informational" will cause a changed status
          source_interface:
            - interface: Vlan10 # must start with capital and no space for vlan number.
          hosts:
            - host: 10.4.0.1
        state: merged
